<?php

$example1 = [

    "LOREM" => [
        "lorem" => "Lorem",
        "ipsum" => "Ipsum",
    ],

    "FOO" => [
        "foo" => "Foo",
        "bar" => "Bar",
    ],
];

$example2 = [

    "bar" => [
        "foo",
        "bar",
        "lorem",
        "ipsum"
    ],
];

$example3 = [
    "foo1" => "bar",
    "foo2" => "bar",
    "foo3" => "bar",
    "foo4" => "bar",
    "foo5" => "bar",
];

$example4 = [
    "foo",
    "bar",
    "lorem",
    "ipsum"
];

$example5 = [
    'foo' => [
        'bar' => [
            'lorem1' => 'ipsum',
            'lorem2' => 'vacum',
        ],
    ],

    'lorem' => 'bar'
];

$lang = [

    "commons" => [
        "home" => "Home",
        "profile" => "Profile",
        "logout" => "Logout",
        "manage_users" => "Manage users",
        "select_interface" => "Select interface",
        "dashboard" => "Dashboard",
        "patients" => "Patients",
        "all_patients" => "All patients",
        "search_patients" => "Search patients",
        "add_patient" => "Add new patient",
        "upcoming_appointments" => "Upcoming Appointments",
        "abnormal_values_menu" => "Abnormal values",
        "appointment_form" => "Appointment form",
        "resources" => "Resources",
        "downloads" => "Downloads",
        "ms_one_to_one" => "MS One to One",
        "adverse_effects_menu" => "Adverse effects",
        "manage_group" => "Manage group",
        "email_notifications" => "Email notifications",
        "user_roles" => "User roles",
        "open_incidents" => "Open incidents",
        "search_incidents" => "Search incidents",
        "new_incident" => "New incident",
        "incident_details" => "Incident details",
        "aes_to_be_reported" => "AEs to be reported",
        "aes_already_reported" => "AEs already reported",
        "aes_already_reported_large" => "Adverse effects already reported",
        "adverse_effects_notif" => "Adverse effects notifications",
        "hcp" => "HCP",
        "hcp_groups" => "HCP groups",
        "footer_terms_link" => "Terns and conditions",
        "footer_privacy_link" => "Privacy policy",
        "footer_cookie_link" => "Cookie policy",
        "footer_site_map_link" => "Site map",
        "footer_contact_us_link" => "Contact us",
        "footer_legal_text_1" => "This site is intended for United States residents only.",
        "footer_legal_text_2" => "All rights reserved.",
        "footer_legal_text_3" => "Lemtrada and Genzyme are registered trademarks of Genzyme Corporation",
        "login" => "Log in",
        "register" => "Register",
        "email" => "Email",
        "password" => "Password",
        "forgot_password" => "Forgot your password?",
        "reset_password" => "Reset password",
        "reset_password_text" => "Enter the email address that you used to register. We'll send you an email with your new password.",
        "send" => "Send",
        "if_need_help" => "If you need help,",
        "contact_us_link" => "contact us.",
        "register_intro_text" => "Health care professionals who register on this website will be able to view and edit the information entered by other health care professionals in the same Medical Center Group. If you are a nurse, you will be asked to invite a physician as part of the registration process. The first health care professional to register in each group will receive \"administrator\" privileges, which will allow them to invite others to join their group, control email notifications, and give others the \"administrator\" role.",
        "personal_info" => "Personal information",
        "pro_info" => "Professional Information",
        "user_info" => "User Information",
        "email_addr" => "Email address",
        "email_conf" => "Email confirmation",
        "first_name" => "First name",
        "surname" => "Surname",
        "medical_id_num" => "Medical ID Number",
        "office_num" => "Office phone",
        "mobile_phone" => "Mobile phone",
        "postal_code" => "Postal code",
        "required" => "Required fields",
        "next" => "Next",
        "type_of_prof" => "Type of professional",
        "medical_center_country" => "Medical center country",
        "medical_center_province" => "Medical center state / province",
        "medical_center_name" => "Medical center name",
        "hcp_group_name" => "HCP group name",
        "input_note_patient_names" => "Please do not use full or partial patient names in this field.",
        "terms_cond_check" => "I accept the",
        "terms_cond_link" => "Terms & Conditions",
        "sign_up" => "Sign up",
        "invite_physician" => "Invite a physician (email)",
        "specialty" => "Specialty",
        "last_appointment" => "last appointment",
        "last_appointment_abrv" => "last appt.",
        "footer_terms_link" => "Terns and conditions",
        "footer_privacy_link" => "Privacy policy",
        "footer_cookie_link" => "Cookie policy",
        "footer_site_map_link" => "Site map",
        "footer_contact_us_link" => "Contact us",
        "footer_legal_text_1" => "This site is intended for country_name residents only.",
        "footer_legal_text_2" => "All rights reserved.",
        "footer_legal_text_3" => "Lemtrada and Genzyme are registered trademarks of Genzyme Corporation",
        "medical_info" => "Medical Information",
        "treatment_start_date" => "Treatment start date",
        "patient_system_id" => "Patient system ID",
        "patient_identifier" => "Patient identifier",
        "phone" => "Phone",
        "birthdate" => "Birthdate",
        "day_date_format" => "dd",
        "month_date_format" => "mm",
        "year_date_format" => "yyyy",
        "sex" => "Sex",
        "patient_legal_text" => "The patient accepts the",
        "legal_terms_link" => "legal terms",
        "health_data" => "Health Data",
        "hypersensivity_drug" => "Hypersensivity to the drug",
        "hiv" => "HIV",
        "active_tuberculosis" => "Active tuberculosis",
        "hepatitis" => "Hepatitis",
        "vaccine" => "Vaccine",
        "pregnancy" => "Pregnancy & contraception",
        "red_blood" => "Red blood cell count",
        "erythrocyte" => "Erythrocyte count",
        "hematocrit" => "Hematocrit",
        "platelets" => "Platelets",
        "white_blood" => "White blood cell count",
        "leukocytes" => "Leukocytes",
        "neutrophils" => "Neutrophils",
        "renal_function" => "Renal function",
        "creatinine" => "Creatinine",
        "proteinuria" => "Proteinuria",
        "hematurias" => "Hematurias",
        "tyroid" => "Tyroid",
        "tsh" => "TSH",
        "t3" => "T3",
        "t4" => "T4",
        "save_and_continue" => "Save & continue later",
        "ineligible_patient" => "Ineligible patient",
        "ineligible_patient_text_1" => "Since the answer to one of the previous questions is \"abnormal\" the patient will be considered ineligible for the program.",
        "ineligible_patient_text_2" => "You can find this patient in the Ineligible Patients tab.",
        "go_back_all_patients" => "Go back to the All patients page",
        "want_enter_data_prev_app" => "I want to enter the data for the previous appointments.",
        "comments" => "Comments",
        "save_patient" => "Save patient",
        "patient_page" => "Patient page",
        "treatment_initiated" => "Treatment initiated",
        "from" => "From",
        "to" => "To",
        "next_appointment" => "Next appointment",
        "months_in_treatment" => "months in treatment",
        "patient_status" => "Patient status",
        "page_of" => "of",
        "health" => "Health care professional",
        "patient_registered" => "Patient registered",
        "appointment_scheduled_date" => "Appointment scheduled date",
        "last_appointment_text" => "Last appointment had abnormal values",
        "any_appointment_text" => "Any appointment had abnormal values",
        "search" => "Search",
        "export_results" => "Export results",
        "search_results" => "Search results",
        "hcp_who_reg" => "HCP who registered",
        "patient_details" => "Patient details",
        "edit" => "Edit",
        "status" => "Status",
        "view_medical_details" => "View medical details used for registration",
        "abnormal_app" => "Abnormal appointments",
        "close" => "close",
        "days_late" => "Days late",
        "number_of_days" => "Number of days late",
        "medical_details" => "Medical details used for registration",
        "app_took_place" => "Appointment took place",
        "go_back_patient_details" => "Go back to Patient details",
        "most_recent_app" => "Most recent appointment",
        "last" => "last",
        "appointment_prog" => "Appointment programmed",
        "comments_from_prev_app" => "Comments from previous appointment",
        "appointment_scheduled" => "Appointment scheduled",
        "note" => "Note",
        "will_remind_thyroid_date_due" => "will remind the user that Thyroid data is due",
        "save" => "Save",
        "go_back_upcoming_app" => "Go back to upcoming appointments",
        "app_details" => "Appointment details",
        "app_data_recorded" => "Appointment data recorded in platform",
        "report_to_pharma" => "Report to pharmacovigilance",
        "note_if_the_anwer_pharmacovigilance" => "If the answer to any of the previous questions is \"abnormal\" the appointment will be reported to pharmacovigilance.",
        "contact" => "Contact",
        "download" => "Download",
        "invite_ms_one_to_one" => "Invite patient to MS One to One",
        "invite_ms_one_to_one_text" => "If you would like to invite a patient to the MS One to One program, please enter their email address below and an invitation to the program will be emailed to them.",
        "list_of_invited" => "List of invited patients",
        "date" => "Date",
        "patient_email" => "Patient email",
        "hcp_group_member" => "HCP group member",
        "info_related_reporting_ae" => "Information related to reporting the AE",
        "info_related_reporting_ae_text" => "To report a potential Adverse Event to Pharmacovigilance, please use the contact information below.",
        "invite_hcp" => "Invite HCP",
        "invite_hcp_intro" => "Invite HCP to join group",
        "invite_hcp_text" => "To invite someone else to join your group, please enter their email address below. As a reminder, the name of your Medical Center Group is",
        "list_invited_hcp" => "List of invited HCP",
        "resend_appli" => "Resend application",
        "resend" => "Resend",
        "accepted" => "Accepted",
        "notifications" => "Notifications",
        "notifications_text" => "Notifications about appointments with abnormal values must go to at least one doctor. Other appointment notifications must go to at least one HCP.",
        "upcoming_delayed_missed" => "Upcoming, delayed and missed appointments",
        "hcp_group_mambers" => "HCP group members",
        "primary_hcp" => "Primary HCP",
        "hcp_administrators" => "hcp administrators",
        "primary_hcp_text" => "The Primary HCP will always receive notifications about Appointments with abnormal values. At least one doctor must have this role (but more than one person can be given this role).",
        "hcp_administrators_text" => "HCP administrators have the ability to invite other HCPs, control who receives notifications, and assign other HCP Administrators and Primary HCP doctors.",
        "hcp_system_id" => "HCP system ID",
        "name" => "Name",
        "medical_center_group_name" => "Medical center group name",
        "contact_details" => "Contact details",
        "contact_me_by" => "Contact me by",
        "change_your_pass" => "Change your password",
        "technical_help_desk" => "Technical help desk",
        "contact_intro" => "Please use this contact form only if you have a technical question. This email account will not be able to respond to inquiries about OneKey. If you have a question about your OneKey account, please contact OneKey at",
        "subject" => "Subject",
        "new_password" => "New password",
        "repeat_new_password" => "repeat new Password",
        "filter_by" => "Filter by",
        "incident_generated" => "Incident generated",
        "task_due_date" => "Task due date",
        "task_subject" => "Task subject",
        "incident_type" => "Incident type",
        "comp_tasks" => "Comp. tasks",
        "ab_abrv" => "AE",
        "incident_id" => "Incident ID",
        "external_nurse_name" => "External nurse name",
        "task_comments" => "Task Comments",
        "new_adverse_effect" => "New adverse effect",
        "task_id" => "Task ID",
        "patient_id" => "Patient ID",
        "appointment_status" => "Appointment status",
        "appointment_completed" => "Appointment completed",
        "save_task_completed" => "Save task as complete",
        "save_create_task" => "Save & create a new task",
        "prev_tasks" => "Previous tasks",
        "task_completion" => "Task completion",
        "external_nurse" => "External nurse",
        "patient_personal_info" => "Patient personal information",
        "view_patient_details" => "View patient details",
        "history_of_app" => "History of appointments",
        "adverse_effect_internal_com" => "Adverse effect internal Comments",
        "adverse_effects_notes" => "Adverse effect notes",
        "new_task" => "New task",
        "time" => "Time",
        "marked_as_ae" => "Marked as AE",
        "ae_comment" => "AE comment",
        "pharmaco_vigilance" => "Pharmaco-vigilance",
        "ae_reported" => "AE reported",
        "notify_pharmaco_vigilance" => "Notify pharmacovigilance",
        "year_of_birth" => "Year of birth",
        "pacient_reg" => "Pacient registered ",
        "scheduled_appointment_date" => "Scheduled appointment date",
        "registration" => "Registration",
        "hcp_office_phone" => "HCP office phone",
        "initial_medical_details" => "Initial medical details",
        "view_tasks" => "View tasks",
        "last_notifications" => "Last notifications",
        "search_hcp" => "Search HCP",
        "hcp_group" => "HCP group",
        "date_of_reg" => "Date of registration",
        "mc_country" => "MC country",
        "mc_sate" => "MC state /province",
        "mc_name" => "MC Name",
        "reset_act_link" => "Reset activation link",
        "search_hcp_group" => "Search HCP group",
        "export" => "Export",
        "groups_within_mc" => "Groups within MC",
        "new_users" => "New users",
        "new_user" => "New user",
        "new_user_text" => "Using the button below, you can create a new user and assign them roles such as nurse, country manager, or global manager.",
        "list_invited_users" => "List of invited users",
        "user_name" => "User name",
        "user_email" => "User email",
        "role" => "Role",
        "appointment_entered_correctly" => "The appointment data you entered was correctly saved.",
        "report_to_pharma_text" => "To report a potential Adverse Event to Pharmacovigilance, please use the contact information below. You may be contacted by a nurse for more information about the abnormal value that was just recorded.",
        "notify" => "Notify",
        "appointment_notify_text" => "In the appointment you just completed, \"abnormal\" was selected in at least one of the parameters. The following list shows those who have already received an email notification and allows you to also notify others (clicking SEND next to a user's name will automatically send them an email).",
    ],

    "admin_user_rol" => [
        "admin" => "Admin",
        "genzyme" => "Genzyme",
        "en" => "External nurse",
    ],

    "dashboard_keys" => [
        "appointments" => "Appointments",
        "current_patients" => "Current patients",
        "ineligible_patients" => "Ineligible patients",
        "in_registration_patients" => "Patients in registration",
        "total_patients" => "Total patients",
        "completed_appointemnts" => "Completed appointments",
        "pending_appointments" => "Pending appointments",
        "missed_appointments" => "Missed appointments",
        "delayed_appointments" => "Delayed appointments",
        "patients_abnormal_values" => "Patients with abnormal values",
        "appointments_abnormal_values" => "Appointments with abnormal values",
        "medical_centers" => "Medical centers",
        "medical_center" => "Medical center",
        "active_groups" => "Groups within MC",
        "incidents" => "Incidents",
        "adverse_effects" => "Adverse effects to be reported",
        "incidents_adverse_effects" => "Incidents marked as Adverse Effects",
    ],

    "hcp_user_types" => [
        "nurse" => "Nurse",
        "doctor" => "Doctor",
    ],

    "patient_status" => [
        "current" => "Current",
        "in_registration" => "In Registration",
        "ineligible" => "Ineligible",
        "completed" => "Completed",
    ],

    "sex_options" => [
        "male" => "Male",
        "female" => "Female",
    ],

    "appointment_status" => [
        "pending" => "Pending",
        "completed" => "Completed",
        "missed" => "Missed",
        "pre_application" => "Pre-application",
    ],

    "appointment_answer_values" => [
        "normal" => "Normal",
        "abnormal" => "Abnormal",
    ],

    "hcp_user_specialty" => [
        "neurology" => "Neurology",
    ],

    "errors" => [
        "error_forms_general" => "Please check the form, there are incorrect or unfilled fields.",
    ],

    "mails" => [
        "" => "",
    ],

];
